site_name: Tree-based Pipeline Optimization Tool
site_url: http://rhiever.github.io/tpot
site_author: Randal S. Olson
site_description: TPOT is a Python tool that automatically creates and optimizes machine learning pipelines using genetic programming.

repo_url: https://github.com/rhiever/tpot

docs_dir: sources
theme: readthedocs

markdown_extensions:
  - tables
  - fenced_code

copyright: Copyright &copy; 2016 <a href="http://www.randalolson.com">Randal Olson</a>

pages:
- Home: index.md
- License: license.md
- Installation: installing.md
- Contributing: contributing.md
- Examples:
  - examples/Using_TPOT_via_the_command_line.md
  - examples/Using_TPOT_via_code.md
  - examples/MNIST_Example.md
  - examples/IRIS_Example.md
  - examples/Titanic_Kaggle_Example.md
  - examples/Custom_Scoring_Functions.md
- Reference:
  - Index: ref_index.md
  - TPOT Object: reference/TPOT.md
  - Pipeline Operators:
    - Models:
      - DecisionTreeClassifier: reference/pipeline_operators/models/classifiers/tree/DecisionTreeClassifier.md
      - RandomForestClassifier: reference/pipeline_operators/models/classifiers/ensemble/RandomForestClassifier.md
      - XGBClassifier: reference/pipeline_operators/models/classifiers/ensemble/XGBClassifier.md
      - SVC: reference/pipeline_operators/models/classifiers/svm/SVC.md
      - kNeighborsClassifier: reference/pipeline_operators/models/classifiers/nearest_neighbors/kNeighborsClassifier.md
      - LogisticRegression: reference/pipeline_operators/models/classifiers/linear_model/LogisticRegression.md
    - Pre-Processing:
      - StandardScaler: reference/pipeline_operators/preprocessing/scaling/StandardScaler.md
      - RobustScaler: reference/pipeline_operators/preprocessing/scaling/RobustScaler.md
      - PolynomialFeatures: reference/pipeline_operators/preprocessing/PolynomialFeatures.md
    - Feature Selection:
      - VarianceThreshold: reference/pipeline_operators/feature_selection/VarianceThreshold.md
      - SelectKBest: reference/pipeline_operators/feature_selection/SelectKBest.md
      - SelectPercentile: reference/pipeline_operators/feature_selection/SelectPercentile.md
      - RFE: reference/pipeline_operators/feature_selection/RFE.md
    - Decomposition:
      - RandomizedPCA: reference/pipeline_operators/decomposition/RandomizedPCA.md
- Changelog: changelog.md
