site_name: TPOT
site_url: http://rasbt.github.io/tpot
site_author: Sebastian Raschka
site_description: TPOT is a Python tool that automatically creates and optimizes Machine Learning pipelines using genetic programming.

repo_url: https://github.com/rhiever/tpot

docs_dir: sources
theme: mkdocs

markdown_extensions:
  - tables
  - fenced_code

copyright: Copyright &copy; 2015 <a href="http://randalolson.com">Randal Olson</a>

pages:
- Home: index.md
- Examples:
  - Using TPOT via the command line: examples/Using_TPOT_via_the_command_line.md
  - Using TPOT via code: examples/Using_TPOT_via_code.md
  - MNIST Example: examples/MNIST_Example.md
  - Custom Scoring Functions: examples/Custom_Scoring_Functions.md
- Changelog: changelog.md
- Installation: installing.md
- Reference:
  - Pipeline Operators:
    - Models:
      - DecisionTreeClassifier: reference/pipeline_operators/models/classifiers/tree/DecisionTreeClassifier.md
      - RandomForestClassifier: reference/pipeline_operators/models/classifiers/ensemble/RandomForestClassifier.md
      - GradientBoostingClassifier: reference/pipeline_operators/models/classifiers/ensemble/GradientBoostingClassifier.md
      - SVC: reference/pipeline_operators/models/classifiers/svm/SVC.md
      - kNeighborsClassifier: reference/pipeline_operators/models/classifiers/nearest_neighbors/kNeighborsClassifier.md
      - LogisticRegression: reference/pipeline_operators/models/classifiers/linear_model/LogisticRegression.md
    - Pre-Processing:
      - StandardScaler: reference/pipeline_operators/preprocessing/scaling/StandardScaler.md
      - RobustScaler: reference/pipeline_operators/preprocessing/scaling/RobustScaler.md
      - PolynomialFeatures: reference/pipeline_operators/preprocessing/PolynomialFeatures.md
    - Feature Selection:
      - VarianceThreshold: reference/pipeline_operators/feature_selection/VarianceThreshold.md
      - SelectKBest: reference/pipeline_operators/feature_selection/SelectKBest.md
      - SelectPercentile: reference/pipeline_operators/feature_selection/SelectPercentile.md
      - RFE: reference/pipeline_operators/feature_selection/RFE.md
    - Decomposition:
      - PCA: reference/pipeline_operators/decomposition/PCA.md
- Contributing: contributing.md
