site_name: TPOT
site_url: http://rhiever.github.io/tpot
site_author: Randal S. Olson
site_description: TPOT is a Python tool that automatically creates and optimizes machine learning pipelines using genetic programming.

repo_url: https://github.com/rhiever/tpot

docs_dir: sources
theme: flatly

markdown_extensions:
  - tables
  - fenced_code

copyright: Copyright &copy; 2016 <a href="http://www.randalolson.com">Randal Olson</a>

pages:
- Home: index.md
- Installation: installing.md
- Using TPOT: Using_TPOT.md
- Examples:
  - examples/MNIST_Example.md
  - examples/IRIS_Example.md
  - examples/Titanic_Kaggle_Example.md
  - examples/Custom_Scoring_Functions.md
- Reference:
  - Documentation: documentation.md
  - Contributing: contributing.md
